import { Project } from './types';

export const projects: Project[] = [
    {
    id: '4lkj34223rf',
    title: 'Medical Biiling Website 🩺',
    src: 'Medical-billing.jpg',
    color: '#fee2e2',
    url: 'https://medicalbywaqas.vercel.app/',
    tech: ['React', 'Tailwind CSS','Typescript' , 'ShadeCn','Framer' ],
    about: 'A sleek medical billing web app with a user-friendly interface for managing appointments, services, and patient interactions.',
    role: 'Frontend ',
  },
  {
    id: '4lkj34256hgf',
    title: 'Learn Wise 📝',
    src: 'Learn-Wise.png',
    color: '#ffedd5',
    url: 'https://learn-wise.vercel.app/',
    tech: ['NextJs-14','Shadcn-ui', 'PostgreSQL','Prisma','Zustand-State-Managment','Mux','Stripe','Uploadthing'],
    about: 'A learning managment application where you can buy and sell courses',
    role: 'Fullstack',
  },
   {
    id: '4lkj342wf33',
    title: 'Omni Food 🍔',
    src: 'Omni food.jpg',
    color: '#fae8ff',
    url: 'https://omnifood-kitchen-website.vercel.app/',
    tech: ['HTML', 'CSS', 'JS', "Scroll-base Animation"],
    about: 'A visually appealing food website with smooth animations and a clean, modern UI.',
    role: 'Frontend',
  },
  {
    id: '4lkj342dvd53',
    title: 'Idea Script 📼',
    src: 'Idea_Script.png',
    color: '#ecfccb',
    url: 'https://idea-script.vercel.app/',
    tech: ['NextJs-14', 'Shadcn-ui','Convex-DB', 'Clerk-Auth','Edge-Store'],
    about: 'Real time idea managment app',
    role: 'Fullstack',
  },
  {
    id: '4lkj34224',
    title: 'Events Lab 🔖',
    src: 'EventsLAB.png',
    color: '#dbeafe',
    url: 'https://eventlab.netlify.app/',
    tech: ['React', 'Firebase'],
    about: 'Find the Latest events near you and Book it with dashoard',
    role: 'Fullstack',

  },
  {
    id: '4lkj3423f33',
    title: 'Expense Tracker 💲',
    src: 'Expense tracker.jpg',
    color: '#dbeafe',
    url: 'https://expensetrackbywaqas.vercel.app/',
    tech: ['React', 'Tailwind Css','Chart js'],
    about: 'A simple and efficient expense tracker web app that helps users manage daily expenses, track spending habits, and maintain better financial control through a clean and intuitive interface.',
    role: 'Frontend',
  },
];

export const color: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
  "#e09f3e",
  "#8338ec",
  "#ff9f1c",
  "#003d5b",
  "#0E9a5b",
  "#ff8a5b",
  "#008a5b",
];