import { Project } from './types';

export const projects: Project[] = [
  {
    id: '4lkj34256hgfajdfs32',
    title: 'InsightFulDoc-SAAS 🛠️',
    src: 'InsightFulDoc-SAAS.png',
    color: '#ddd6fe',
    url: 'https://insight-ful-doc-saas.vercel.app/',
    tech: ['NextJs-14','Shadcn-ui', 'PineconeDB','PostgreSQL','KindeAuth','Prisma','OpenAI','reactPDF','langchain','Stripe','Uploadthing'],
    about: 'A Software as a Service applications helps you to chat with your PDFs using gpt-3.5',
    role: 'Fullstack',
  },
  {
    id: '4lkj34256hgf',
    title: 'Learn Wise 📝',
    src: 'Learn-Wise.png',
    color: '#ffedd5',
    url: 'https://learn-wise.vercel.app/',
    tech: ['NextJs-14','Shadcn-ui', 'PostgreSQL','Prisma','Zustand-State-Managment','Mux','Stripe','Uploadthing'],
    about: 'A learning managment application where you can buy and sell courses',
    role: 'Fullstack',
  },
  {
    id: '4lkj342dvd53',
    title: 'Idea Script 📼',
    src: 'Idea_Script.png',
    color: '#ecfccb',
    url: 'https://idea-script.vercel.app/',
    tech: ['NextJs-14', 'Shadcn-ui','Convex-DB', 'Clerk-Auth','Edge-Store'],
    about: 'Real time idea managment app',
    role: 'Fullstack',
  },
  {
    id: '4lkj34224',
    title: 'Events Lab 🔖',
    src: 'EventsLAB.png',
    color: '#dbeafe',
    url: 'https://eventlab.netlify.app/',
    tech: ['React', 'Firebase'],
    about: 'Find the Latest events near you and Book it with dashoard',
    role: 'Fullstack',

  },
  {
    id: '4lkj342dfd',
    title: 'EatingOut 🍴',
    src: 'eatingOut.png',
    color: '#ddd6fe',
    url: 'https://eatingout-reactapp.netlify.app/',
    tech: ['React', 'Framer', 'Firebase'],
    about: 'Resturent App order food and track the file with dashbaord',
    role: 'Frontend',
  },
  {
    id: '4lkj342wf33',
    title: 'Trend Blend 🛒',
    src: 'TrendBlend.png',
    color: '#fae8ff',
    url: 'https://trendblend.netlify.app/',
    tech: ['React', 'Node.js', 'Express', "Framer", "MongoDB", "RestAPI"],
    about: 'Ecommerece App with CMS',
    role: 'Fullstack',
  },
  {
    id: '4lkj34223rf',
    title: 'Url Shortner 🔗',
    src: 'ShortUrl.png',
    color: '#fee2e2',
    url: 'https://learnwithfaizan.netlify.app/',
    tech: ['React', "EJS", "Node.js", 'Express', "MongoDB", "RestAPI", 'Render', 'vercel'],
    about: 'You can short your URLS',
    role: 'Backend ',
  },
  {
    id: '4lkj3423f33',
    title: 'FileLinker 📩',
    src: 'fileLinker.png',
    color: '#dbeafe',
    url: 'https://file-linker.vercel.app/',
    tech: ['React', 'Firebase', 'ChakraUi','Bootstrap','dayjs'],
    about: 'A FileSharing app to share your files with others',
    role: 'Fullstack',
  },
  {
    id: '4lkj3425f23',
    title: 'Threads Clone 🧑‍💻',
    src: 'threads.png',
    color: '#ddd6fe',
    url: 'https://threads-clone-ten-psi.vercel.app/',
    tech: ['NextJs-13', 'TypeScript','Clerk Auth', 'Uploadthing','TailwindCss'],
    about: 'A social media application where you can share your moments',
    role: 'Fullstack',
  },
  {
    id: '4lkj34256hzxcf',
    title: 'Ecommerce 🏷️',
    src: 'ecommerce.png',
    color: '#008a5b',
    url: 'https://ecommerce-firebase-1.vercel.app/',
    tech: ['Nextjs', 'Shadcn ui', 'Tailwind', 'Firebase'],
    about: 'A Ecommerce Application complete functional with dashboard',
    role: 'Frontend',
  },
  {
    id: '4lkj34256hzzxzxxcf',
    title: 'Markdown Blog 📝',
    src: 'blog.png',
    color: '#0E9a5b',
    url: 'https://insuretermblog.com/',
    tech: ['React', 'Antd', 'Bootstrap', 'Firebase'],
    about: 'A Markdown blog complete functional with dashboard',
    role: 'Frontend',
  },
  {
    id: '4lkj34256hgf',
    title: 'Sticky-Wall 🧱',
    src: 'stickyWall.png',
    color: '#ffedd5',
    url: 'https://sticky-wall.vercel.app/',
    tech: ['ReactJs', 'antd', 'Bootstrap', 'firebase'],
    about: 'A Task Management System helps you manage your tasks',
    role: 'Frontend',
  },
];

export const color: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
  "#e09f3e",
  "#8338ec",
  "#ff9f1c",
  "#003d5b",
  "#0E9a5b",
  "#ff8a5b",
  "#008a5b",
];